"""create users table

Revision ID: 854cf845c973
Revises: 
Create Date: 2025-04-01 13:14:01.040816

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '854cf845c973'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
